services:
  api:
    # get docker image build from ubuntu (amd64)
    image: sonnydocker/myfastapi:ci-cd
    ports:
      - 8000:8000
    environment:
      - DATABASE_HOSTNAME=postgres    # point to postgres database container
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
    depends_on:
      - postgres
  
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes: 
      - postgres-db:/var/lib/postgresql/data 
volumes:
    postgres-db: