"""add phone_num to users table

Revision ID: 4763982c948d
Revises: 2bcdca3833a9
Create Date: 2023-06-01 21:57:37.189695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4763982c948d'
down_revision = '2bcdca3833a9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_num', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_num')
    # ### end Alembic commands ###
